### ISSUE TITLE
https://www.gooodmorningweb.fr/index.xml

### ISSUE THREAD

**Issue by slecache** [pcarion/podcastfr#41]

**Comment by pcarion** [comment]
Processing podcast URL: https://www.gooodmorningweb.fr/index.xml  (issue number: 41)
the url seems to be a RSS URL

podcast found at that URL:
- title: `Goood Morning Web - Le Podcast pour et par les amoureux du web on Goood Morning Web`
- description: `Recent content in Goood Morning Web - Le Podcast pour et par les amoureux du web on Goood Morning We`...

Your submission was successfully added in: `podcasts/goood_morning_web_-_le_podcast_pour_et_par_les_amoureux_du_web_on_goood_morning_web-41.yaml`
The site will be regenerated automatically shortly and your submission will appear soon there

Thank you for your submission!
