### ISSUE TITLE
https://feeds.acast.com/public/shows/no-log

### ISSUE THREAD

**Issue by slecache** [pcarion/podcastfr#42]

**Comment by pcarion** [comment]
Processing podcast URL: https://feeds.acast.com/public/shows/no-log  (issue number: 42)
the url seems to be a RSS URL

podcast found at that URL:
- title: `NO LOG`
- description: `NO LOG est un Podcast natif francophone, pour plonger dans les coulisses du cybermonde.
Le monde cyb`...

Your submission was successfully added in: `podcasts/no_log-42.yaml`
The site will be regenerated automatically shortly and your submission will appear soon there

Thank you for your submission!
