### ISSUE TITLE
https://www.nolimitsecu.fr/feed/podcast/

### ISSUE THREAD

**Issue by slecache** [pcarion/podcastfr#43]

**Comment by pcarion** [comment]
Processing podcast URL: https://www.nolimitsecu.fr/feed/podcast/  (issue number: 43)
the url seems to be a RSS URL

podcast found at that URL:
- title: `NoLimitSecu`
- description: `Podcast dédié à la cyber sécurité`...

Your submission was successfully added in: `podcasts/nolimitsecu-43.yaml`
The site will be regenerated automatically shortly and your submission will appear soon there

Thank you for your submission!
