### ISSUE TITLE
https://feed.ausha.co/BDVYOij2WP05

### ISSUE THREAD

**Issue by SylvainCoudert** [pcarion/podcastfr#52]

**Comment by pcarion** [comment]
Processing podcast URL: https://feed.ausha.co/BDVYOij2WP05  (issue number: 52)
the url seems to be a RSS URL

podcast found at that URL:
- title: `PunkinDev`
- description: `Bienvenue sur le podcast Punkin dev. Vous trouverez ici des récits de la vie de dev, des retours d'e`...

Your submission was successfully added in: `podcasts/punkindev-52.yaml`
The site will be regenerated automatically shortly and your submission will appear soon there

Thank you for your submission!
