### ISSUE TITLE
https://feed.ausha.co/BnJeLCJa57vR

### ISSUE THREAD

**Issue by SylvainCoudert** [pcarion/podcastfr#53]

**Comment by pcarion** [comment]
Processing podcast URL: https://feed.ausha.co/BnJeLCJa57vR  (issue number: 53)
the url seems to be a RSS URL

podcast found at that URL:
- title: `Les enflures de la tech`
- description: `En marge du SunnyTech 2019, j'ai eu la chance de rencontrer Shirley (https://twitter.com/ShirleyAlmC`...

Your submission was successfully added in: `podcasts/les_enflures_de_la_tech-53.yaml`
The site will be regenerated automatically shortly and your submission will appear soon there

Thank you for your submission!
