### ISSUE TITLE
Is your workflow broken?

### ISSUE THREAD

**Issue by newsoft** [pcarion/podcastfr#82]
I'm trying to update the NoLimitSecu podcast links, but I am unable to pass the presubmit checks.

I suspect that your integration pipeline cannot pull our icon due to firewalling, but that might be a red herring.

```
...
(node:2429) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

>palette retrieved>image url>https://www.nolimitsecu.fr/wp-content/uploads/2014/07/NolimitSecu-1400.png>found>true
Error: Resource not accessible by integration
```

**Comment by pcarion** [comment]
Processing podcast URL: Is your workflow broken?  (issue number: 82)

**Error**: the podcast URL is not valid

**Error**: error during processing of the podcast URL

**Error**: processing error: invalid URL: Is your workflow broken?

if you see an error in the URL, you can update the title of the ticket with the proper URL
someone will review that error shortly in case this is an internal error

Thank you for your submission!

**Comment by pcarion** [comment]
Your change has been merged manually. It is not a fw issue: it seems non owner cannot have their PR merged automatically. Looking for a solution.

Thanks again for your contribution!
